#include "CallbackProxyStartStopWorkshopItemsPlaytimeTracking.h"

class UCallbackProxyStartStopWorkshopItemsPlaytimeTracking;

UCallbackProxyStartStopWorkshopItemsPlaytimeTracking* UCallbackProxyStartStopWorkshopItemsPlaytimeTracking::SteamWorkshop_StartStopItemsPlaytimeTracking(const TArray<FSteamUGCItemId>& itemIds, bool bStartPlaytimeTracking) {
    return NULL;
}

UCallbackProxyStartStopWorkshopItemsPlaytimeTracking::UCallbackProxyStartStopWorkshopItemsPlaytimeTracking() {
}

