#pragma once
#include "CoreMinimal.h"
#include "FUWorksHTTPResponse.generated.h"

UENUM(BlueprintType)
enum class FUWorksHTTPResponse : uint8 {
    Unknown,
    Continue,
    SwitchProtocol,
    Ok,
    Created,
    Accepted,
    Partial,
    NoContent,
    ResetContent,
    PartialContent,
    Ambiguous,
    Moved,
    Redirect,
    RedirectMethod,
    NotModified,
    UseProxy,
    RedirectKeepVerb,
    BadRequest,
    Denied,
    PaymentReq,
    Forbidden,
    NotFound,
    BadMethod,
    NoneAcceptable,
    ProxyAuthReq,
    RequestTimeout,
    Conflict,
    Gone,
    LengthRequired,
    PrecondFailed,
    RequestTooLarge,
    UriTooLong,
    UnsupportedMedia,
    TooManyRequests,
    RetryWith,
    ServerError,
    NotSupported,
    BadGateway,
    ServiceUnavail,
    GatewayTimeout,
    VersionNotSup,
};

